n1 = int(input('Primeiro valor: '))
n2 = int(input('Segundo valor: '))
n3 = int(input('Terceiro valor: '))
mi = min(n1, n2, n3)
ma = max(n1, n2, n3)
print(f'O menor valor digitado foi {mi}')
print(f'O maior valor digitado foi {ma}')
