salario = float(input('Entre com o valor do salário bruto: R$ '))
ir = float(input('Entre com o desconto do IR: '))
inss = float(input('Entre com o desconto do INSS: '))
am = float(input('Entre com o valor do Auxilio Moradia: R$ '))
aa = float(input('Entre com o valor do Auxilio Alimentação: R$ '))
print('*'*48)
print('{:<33}= R$ {}'.format('Salário Bruto', salario))
print('*'*48)

print('Descontos:')
print('{:<33}= {:.2f}%'.format('Imposto de Renda', ir))
print('{:<33}= {:.2f}%\n'.format('Previdencia social', inss))
print('Auxilios:')
print('{:<33}= R$ {:.2f}'.format('Moradia:', salario))
print('{:<33}= R$ {:.2f}'.format('Alimentação', salario))
print('*'*48)
liquido = salario - salario*ir/100 - salario*inss/100 + am + aa
print('{:<33}= R$ {:.2f}'.format('Salário Líquido', liquido))
print('*'*48)
